name: Create UPM Branch

on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:

  create-upm-branch:
  
    name: update upm branch
    
    runs-on: ubuntu-latest

    env: 
      PKG_ROOT: Packages/net.shiftall.pfsignal

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: 'true'

      - name: update upm branch
        run: |
          echo '### head info'
          git log -1
          echo '### split upm branch'
          git subtree split -P "$PKG_ROOT" -b upm
          echo '### update remote upm branch'
          git push origin upm

      - name: Notify to Typetalk
        if: always()
        uses: ymmtyuhei/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 143556
          message: "${{ github.job }} ${{ job.status }}"
