name: Create Unity Package

on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:

  create-unity-package:
  
    name: create unity package
    
    runs-on: ubuntu-latest

    env: 
      PKG_ROOT: Packages/net.shiftall.pfsignal

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: 'true'

      - run: find "${{env.PKG_ROOT}}/" -name \*.meta >> metaList

      - run: mkdir a

      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'a/PFSignal.unitypackage'
          include-files: metaList

      - uses: actions/upload-artifact@master
        with:
          path: a
          name: package

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "${{env.PKG_ROOT}}/package.json"
            prop_path: "version"

      # - name: Create release tag
      #   id: tag
      #   run: |
      #     echo "::set-output name=release_tag::Build_$(TZ=Asia/Tokyo date +"%Y%m%d_%H%M")"

      - name: Create release and upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.prop }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: a/**

      - name: Notify to Typetalk
        if: always()
        uses: ymmtyuhei/typetalk-action@develop
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 143556
          message: "${{ github.job }} ${{ job.status }}"